# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTCClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u73ed\u7ea7\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='PTCClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u6559\u5ba4\u540d')),
                ('wifi', models.CharField(max_length=16, verbose_name='\u6559\u5ba4WIFI')),
                ('position', models.CharField(blank=True, max_length=16, verbose_name='\u6559\u5ba4\u4f4d\u7f6e\u5750\u6807')),
            ],
            options={
                'verbose_name': '\u6559\u5ba4',
                'verbose_name_plural': '\u6559\u5ba4',
            },
        ),
        migrations.CreateModel(
            name='PTCRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u89d2\u8272\u540d')),
            ],
            options={
                'verbose_name': '\u89d2\u8272',
                'verbose_name_plural': '\u89d2\u8272',
            },
        ),
        migrations.CreateModel(
            name='PTCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u59d3\u540d')),
                ('tel', models.CharField(max_length=16, verbose_name='\u7535\u8bdd')),
                ('pwd', models.CharField(max_length=16, verbose_name='\u5bc6\u7801')),
                ('pClass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClass', verbose_name='\u73ed\u7ea7')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCRole', verbose_name='\u89d2\u8272')),
            ],
        ),
    ]
