# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTCLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u8bfe\u7a0b\u540d')),
                ('startTime', models.DateTimeField(verbose_name='\u4e0a\u8bfe\u65f6\u95f4')),
                ('endTime', models.DateTimeField(verbose_name='\u4e0b\u8bfe\u65f6\u95f4')),
                ('pClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClass', verbose_name='\u73ed\u7ea7')),
                ('pClassRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClassRoom', verbose_name='\u6559\u5ba4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u5b89\u6392',
                'verbose_name_plural': '\u8bfe\u7a0b\u5b89\u6392',
            },
        ),
        migrations.CreateModel(
            name='PTCRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTime', models.DateTimeField(auto_now=True, verbose_name='\u6253\u5361\u65f6\u95f4')),
                ('recordWifi', models.CharField(max_length=16, verbose_name='\u6253\u5361WIFI')),
                ('recordPosition', models.CharField(blank=True, max_length=16, verbose_name='\u6253\u5361\u5750\u6807')),
                ('recordLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCLesson', verbose_name='\u8bfe\u7a0b\u5b89\u6392')),
            ],
            options={
                'verbose_name': '\u6253\u5361\u8bb0\u5f55',
                'verbose_name_plural': '\u6253\u5361\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='PTCResetPWDApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resetState', models.BooleanField(default=False, verbose_name='\u662f\u5426\u91cd\u7f6e')),
                ('applyTime', models.DateTimeField(auto_now=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5bc6\u7801\u91cd\u7f6e\u7533\u8bf7',
                'verbose_name_plural': '\u5bc6\u7801\u91cd\u7f6e\u7533\u8bf7',
            },
        ),
        migrations.AlterModelOptions(
            name='ptcuser',
            options={'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
        migrations.AddField(
            model_name='ptcresetpwdapply',
            name='applyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCUser', verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AddField(
            model_name='ptcrecord',
            name='recordUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCUser', verbose_name='\u6253\u5361\u4eba'),
        ),
        migrations.AddField(
            model_name='ptclesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCUser', verbose_name='\u8001\u5e08'),
        ),
    ]
