# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0003_auto_20170415_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptclesson',
            name='pClassRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClassRoom', verbose_name='\u6559\u5ba4\u4fe1\u606f'),
        ),
    ]
