# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0004_auto_20170418_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptclesson',
            name='name',
            field=models.CharField(max_length=16, verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
    ]
