# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0005_auto_20170418_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptclesson',
            name='pClass',
        ),
        migrations.RemoveField(
            model_name='ptclesson',
            name='pClassRoom',
        ),
    ]
