# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0006_auto_20170418_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptclesson',
            name='pClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClass', verbose_name='\u73ed\u7ea7'),
        ),
        migrations.AddField(
            model_name='ptclesson',
            name='pClassRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClassRoom', verbose_name='\u6559\u5ba4\u4fe1\u606f'),
        ),
    ]
