# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0007_auto_20170418_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptcclassroom',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='\u6559\u5ba4\u540d'),
        ),
    ]
