# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0008_auto_20170420_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptcclass',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='\u73ed\u7ea7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='ptclesson',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='ptcrole',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='\u89d2\u8272\u540d'),
        ),
        migrations.AlterField(
            model_name='ptcuser',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='\u59d3\u540d'),
        ),
    ]
