# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0009_auto_20170420_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptcuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
