# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0010_ptcuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptcuser',
            name='tel',
            field=models.CharField(blank=True, max_length=11, verbose_name='\u7535\u8bdd'),
        ),
    ]
