# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0011_auto_20170420_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptclesson',
            name='pushed',
            field=models.BooleanField(default=False, verbose_name='\u6253\u5361\u7edf\u8ba1\u5df2\u63a8\u9001'),
        ),
        migrations.AlterField(
            model_name='ptclesson',
            name='pClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClass', verbose_name='\u73ed\u7ea7'),
        ),
        migrations.AlterField(
            model_name='ptclesson',
            name='pClassRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.PTCClassRoom', verbose_name='\u6559\u5ba4\u4fe1\u606f'),
        ),
    ]
